// <auto-generated />
namespace GameStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201706080 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201706080));
        
        string IMigrationMetadata.Id
        {
            get { return "201706080010335_2017-06-08-0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
