// <auto-generated />
namespace GameStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration201706070 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration201706070));
        
        string IMigrationMetadata.Id
        {
            get { return "201706070251551_migration 2017-06-07-0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
